### PR TITLE
Some AI improvements (v2)

### PR DESCRIPTION
**Pull request by V10lator**
This is the successor of #216

### CODE REVIEW

**Review by Tschipp — APPROVED** [review]

**Review by Tschipp — CHANGES_REQUESTED** [review]
Looking good mostly: just two things:

- GenericAIEatGrass is missing the getFed() check that it used to have.
- GenericAIPanic needs to be executed when the cows don't have a target. With this change the panic AI is never executed for cows.

**Comment by V10lator** [comment]
> GenericAIPanic needs to be executed when the cows don't have a target. With this change the panic AI is never executed for cows.

Could you point out my mistake, please? I seem to fail to see what I did wrong.

//EDIT: NVM, found it.

**Review by Tschipp — APPROVED** [review]

**Comment by Tschipp** [comment]
Looks good. Will pull it and probably release an update later today, thanks for your work.

**Comment by Tschipp** [comment]
Just testing it now and noticed that the AI gets executed significantly less because the timer also gets reset if the rng check fails. This didn't used to be like this and now the AI feels very unresponsive. Will make some changes.

**Pull request merged**
