### PR TITLE
Some AI improvements

### PR DESCRIPTION
**Pull request by V10lator**
Still unsure if I should make a pull request for 24aa0cfffbee6535d1485fe7b4bfbd9e961241d3 - any thoughts?

### CODE REVIEW

**Comment by Tschipp** [comment]
I'm gonna pull this one at a later point, so probably next update.

**Review by Tschipp — COMMENTED** [review]
The current AI searches in a 16x3x16 area (depending on the range). I'm not sure if it's really necessary to search in the full 16x16x16 area, as most of the time the target blocks are on a similar y with the animal. Also what new AI are you working on?

**Comment by capnkirok** [comment]
That's a pretty significant increase in resource usage... and animals should only be able to find what they can see.

**Comment by V10lator** [comment]
@Tschipp I thought so, too, but on this example the chickens are sleeping on the grass with the 16x3x16 code but with the 16x16x16 code they go into the house (which contains nests and straw) :


So the current 3 layer searching seems to not work and increasing is a working solution. If you find a better fix that would ofc. be great.

A preview for the AI I'm working on (didn't test if it works) : https://github.com/V10lator/animaniamod/commit/6aef776bf1e9a0fee2b1ae86770f77114bf289a6 - here they need to search more down as to find cave entries.

**Comment by Tschipp** [comment]
I think we will handle most cases if we just increase the up/down search range to 5 blocks, and it will still not impact performance too much.

**Comment by V10lator** [comment]
I thought about smaller values, too, but hardcoding seems wrong (if someone configures his search range to <5 he might not like the result). What about searchrange / 2 (so 8 by default) ?

Btw: Did someone measure the performance impact? I didn't but my completely underpowered server (4x 1.3 ghz arm8 cpu, 2gb ram, 60+ mods) didn't seem to lag more than before.

//EDIT: Also performance increased less than you might think. Before it searched max 16x16x3x2=1536 blocks while now it searches max 16x16x16=4096 blocks... But take this numbers with a grain of salt as these are max numbers and the new search algo works different (searching primary and secondary block in the same loop, that's why the x2 is gone ;) ).

**Comment by Tschipp** [comment]
Oh, didn't even see the change you made to secondary, see this was done deliberately with two loops. We want to have it so the animals prioritize troughs over other food blocks. I made this change because animals would keep trying to eat tall grass blocks and drink from sources outside of their pen, just because the search algorithm found them before the troughs. With two loops it completely searches for the primary, and only then searches for the secondary.

**Comment by V10lator** [comment]
The bug doesn't reappear: In the loop it checks the primary block first. If the primary doesnt match and no secondary has been found till now it will check the secondary and if it matches it won't exit the loop but continue searching for primary. So if the loop finds a primary later on it will use that one instead of the cached secondary and only if the loop finishes without finding a primary it will use the cached secondary. ;)

//EDIT:
Code is probably better than me explaining: Here it checks for secondary if primary and secondary not found yet inside of the loop: https://github.com/V10lator/animaniamod/blob/shelter-ai-v2/src/main/java/com/animania/common/entities/generic/ai/GenericAISearchBlock.java#L179

If a primary is found inside of the loop it exits here: https://github.com/V10lator/animaniamod/blob/shelter-ai-v2/src/main/java/com/animania/common/entities/generic/ai/GenericAISearchBlock.java#L175

And this happens after the loop (cause of the return statement shown above this code will never run if a primary has been found) : https://github.com/V10lator/animaniamod/blob/shelter-ai-v2/src/main/java/com/animania/common/entities/generic/ai/GenericAISearchBlock.java#L201

**Comment by Tschipp** [comment]
Ah, I it now, thanks for the explanation.

**Comment by Tschipp** [comment]
Btw, I like the height search range with searchrange / 2. seems reasonable. Btw, I just fixed #220, so there will probably be conflicts.

**Comment by V10lator** [comment]
Allright, I made a new branch with newest upstream changes and merged my commits to that. Also I changed the commit "￼GenericAIearchBlock: Search more in a 3D space." to implement the fix commit right after it and search in searchRange / 2 on the y axis. So I'll close this one and open a new pull request.

**Pull request closed without merging**
