### PR TITLE
Better DesirePaths interaction.

### PR DESCRIPTION
**Pull request by V10lator**
This brings the DesirePath interaction in line with what DesirePaths does to vanilla sheeps. See https://github.com/Corosauce/DesirePaths/blob/1.12.x/src/main/java/com/corosus/desirepaths/ai/EntityAIEatGrassExtended.java#L126 for details.

There's also a pull request pending for DesirePath so they won't attach the AI shown above to Animania sheeps at https://github.com/Corosauce/DesirePaths/pull/7

### CODE REVIEW

**Comment by Corosauce** [comment]
FYI this method of invoking another mods code introduces my desirepaths mod as a compile time dependency to their project which they probably arent fond of, you can avoid this with some cached reflection use, heres a working example on how to go about this: https://github.com/Corosauce/CoroUtil/blob/1.12.x/src/main/java/CoroUtil/util/CoroUtilCompatibility.java#L65-L95

**Review by Tschipp — CHANGES_REQUESTED** [review]
I agree with Coro. Please edit so that it uses reflection.

**Comment by V10lator** [comment]
Sure, just one question: Is there already some reflection helper in animania I could reuse for that?

**Comment by Tschipp** [comment]
Yes, there is ReflectionUtil https://github.com/capnkirok/animaniamod/blob/1.12/src/main/java/com/animania/common/helper/ReflectionUtil.java written by Choonster

**Review by Tschipp — APPROVED** [review]

**Pull request merged**
