### PR TITLE
Cache mate UUID for rabbits

### PR DESCRIPTION
**Pull request by V10lator**
Java Profiler shows the dataManager access in getMateUniqueId() to be a hotpath, so let's cache its reply

### CODE REVIEW

**Comment by V10lator** [comment]
BTW: Way hotter paths are genericAISeachBlock.searchForDestination() with its many calls to world.getBlockState() and GenericAIFindWater.shouldMoveTo() also with its call to world.getBlockState(). Sadly I don't know your codes good enough to improve this but it's something you might really want to look into.

**Comment by Tschipp** [comment]
Yes, the AI is expensive, but it has been improved greatly since last release. We used to search for block positions up to three times per call, now we only do it once.

**Comment by Tschipp** [comment]
And is this only a problem with rabbits?

**Comment by V10lator** [comment]
> And is this only a problem with rabbits?

I saw it with rabbits only but I also didn't do much testing, so take it with a grain of salt.

**Comment by V10lator** [comment]
I'm currently experimenting with code optimizations at https://github.com/V10lator/animaniamod/commits/AI-cache - If you have any input on what I do there I would welcome any feedback. :)

**Pull request merged**
